config/routes.rb
Rails.application.routes.draw do
  ### Home
  get '/', to: 'users#home', as: 'root'

  ### Users - Signup
  get '/users/new', to: 'users#new', as: 'signup'
  resources :users, only: [:create]

  ### Sign In
  get '/signin', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get "/auth/google_oauth2/callback", to: "sessions#create"

  ### Book - Popular
  get '/books/popular', to: 'books#popular', as: 'most_popular_books'

  ### Books - Index, Show, Update, Destroy
  resources :books, only: [:index, :show, :update, :destroy]

  ### Books - New, Create, Show from Google Search
  get '/books/search/new', to: 'books#new_search', as: 'new_book_search'
  post '/books', to: 'books#create_search', as: 'create_book_search'
  get '/books/search/:identifier', to: 'books#show_search', as: 'book_search'

  ### User Book Activity - Update 
  resources :user_books, only: [:update]

  ### Book Reviews - New, Create, Edit, Update, Destroy
  resources :books, only: [:show] do 
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

  ### Users Shelves - Show
  resources :users, only: [:show] do
    resources :shelves, only: [:show]
  end

  ### Shelves - New, Create, Edit, Update, Destroy
  resources :shelves, except: [:index, :show]

end

app/models/user.rb
class User < ApplicationRecord
  ### Associations ###
  has_many :user_books
  has_many :books, through: :user_books
  has_many :reviews, through: :user_books
  has_many :shelves

  ### Secure Password ###
  has_secure_password

  ### Validations ###
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :email, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  ### Building and Updating Associations ###
  def add_shelf(shelf_name)
    self.shelves.create(name: shelf_name)
  end

  def destroy_empty_shelves
    self.shelves.each do |shelf|
      shelf.destroy if shelf.books.empty?
    end
  end

  ### Friendly Name ###
  def firstname
    self.name.split(' ')[0]
  end


  def has_book?(book)
    self.books.find_by(identifier: book.identifier)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login  # Require login except with home, new or create action
  skip_before_action :require_login, only: [:home, :new, :create]

  before_action :valid_user, only: [:show]

  ### Home page with sign in and sign up for users that are not logged in
  def home
    if logged_in?
      redirect_to user_path(current_user)   # Redirect to user show page if logged in
    else
      render layout: 'welcome'              # Render home view with welcome layout
    end
  end

  ### Render sign up form
  def new
    if logged_in?
      redirect_to user_path(current_user)   # Redirect to user show page if logged in
    else      
      @user = User.new                      # Stub a new user
      render layout: 'welcome'              # Render sign up form with welcome layout
    end  
  end

  ### Create a new user from info in sign up form
  def create
    @user = User.new(user_params)     # Instantiate a new user

    if @user.save                     # If user saves log them in by adding their id to the session hash
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new', layout: 'welcome' # If user does not save re-render sign up form with errors
    end

  end

  ### Render user show page
  def show
    @user = User.find(params[:id])  # Find user's page to render
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.html.erb
  <!-- *********************  Error Messages  ********************* -->
  <%if object && object.errors.any?%>
    <div class="error-text wrapper clearfix">
      <%=object.errors.full_messages.to_sentence%>
    </div> <!--  .flash  -->
  <%end%>

app/views/users/_large_logo_and_title.html.erb
<div class="large-logo-title">
  <!--  Logo  -->
  <div class="large-logo clearfix">
    <%= image_tag('bookshelf-logo-color.png')%>
  </div> 

  <!--  Title  --> 
  <div class="clearfix">
    <h1 class="large-title" ><%=title%></h1>
  </div>
  
</div> <!--  .large-logo-title  -->

app/views/users/home.html.erb
<div class="centered-div">
  <!-- *********************  Large Name & Logo  ********************* -->
  <%= render 'users/large_logo_and_title', {title: 'Bookshelf'} %>

  <!-- *********************  Login and Signup Buttons  ********************* -->
  <div class="details">
    <!--  App Description  -->
    <p>Collect, organize and track the books you read.</p>

    <!--  Sing-in and Sign-up buttons  -->
    <div class="buttons">
      <%= link_to "Sign In", signin_path, class: 'button' %>
      <%= link_to "Google Sign In", "/auth/google_oauth2", class: 'button'%>
      <%= link_to "Sign Up", signup_path, class: 'button'%>
    </div> <!--  .buttons  -->
    
  </div> <!--  .details  -->
</div> <!--  .centered  -->

app/views/users/new.html.erb
<div class="centered-div">
  <!-- *********************  Large Name & Logo  ********************* -->
  <%= render 'users/large_logo_and_title', {title: 'Sign Up'} %>

  <!-- *********************  Error Messages  ********************* -->
  <%= render 'users/errors', {object: @user} %>

  <!-- *********************  Login and Signup Buttons  ********************* -->
  <div class="details">
    <%= form_for @user do |f| %>
      <!-- Name -->
      <div class="welcome-forms">
        <%= f.label 'Name' %><br>
        <%= f.text_field :name%>
      </div>

      <!-- Email -->
      <div class="welcome-forms">
        <%= f.label 'Email' %><br>
        <%= f.text_field :email%>
      </div>

      <!-- Password -->
      <div class="welcome-forms">
        <%= f.label 'Password' %><br>
        <%= f.password_field :password%>
      </div>
      
      <!-- Submit -->
      <div class="welcome-forms">
        <%= f.submit "Sign Up", class: "button"%>
      </div>
    <% end %>
  </div> <!--  .details  -->
</div> <!--  .centered  -->

app/views/users/show.html.erb
<!-- *********************  Search Error Messages  ********************* -->
<%if !!flash[:alert]%>
  <div class="error-text wrapper centered clearfix">
    <%=flash[:alert]%>
  </div> <!-- flash -->
<%end%>

<!-- *********************  Header and New Shelf Button  ********************* -->
<div class='sub-section'>
  <h1><%=@user.firstname%>'s Books</h1>
  <%=(link_to 'Create a Shelf', new_shelf_path, class: "button", id: "new_shelf") if @user == current_user%>
</div>

<!-- *********************  User's Unsorted Books  ********************* -->
<% if unsorted_books(@user).any?%>
<div class = 'sub-section'>
  <%= render 'books/grid', {books: unsorted_books(@user), search: false} %>
</div>
<%end%>

<!-- *********************  Remaining books, sorted by shelf  ********************* -->
<% @user.shelves.each do |shelf| %>
  <div class='sub-section'>
    <h4 class = "centered"><%=link_to "#{shelf.name}", user_shelf_path(@user,shelf)%></h4>
    <%= render 'books/grid', {books: shelf.books, search: false} %>
  </div>
<%end%>