config/routes.rb
Rails.application.routes.draw do
  ### Home
  get '/', to: 'users#home', as: 'root'

  ### Users - Signup
  get '/users/new', to: 'users#new', as: 'signup'
  resources :users, only: [:create]

  ### Sign In
  get '/signin', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get "/auth/google_oauth2/callback", to: "sessions#create"

  ### Book - Popular
  get '/books/popular', to: 'books#popular', as: 'most_popular_books'

  ### Books - Index, Show, Update, Destroy
  resources :books, only: [:index, :show, :update, :destroy]

  ### Books - New, Create, Show from Google Search
  get '/books/search/new', to: 'books#new_search', as: 'new_book_search'
  post '/books', to: 'books#create_search', as: 'create_book_search'
  get '/books/search/:identifier', to: 'books#show_search', as: 'book_search'

  ### User Book Activity - Update 
  resources :user_books, only: [:update]

  ### Book Reviews - New, Create, Edit, Update, Destroy
  resources :books, only: [:show] do 
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

  ### Users Shelves - Show
  resources :users, only: [:show] do
    resources :shelves, only: [:show]
  end

  ### Shelves - New, Create, Edit, Update, Destroy
  resources :shelves, except: [:index, :show]

end

app/models/book.rb
class Book < ApplicationRecord
  ### Associations ###
  has_many :user_books
  has_many :users, through: :user_books
  has_many :reviews, through: :user_books
  has_many :book_shelves
  has_many :shelves, through: :book_shelves
  belongs_to :genre
  belongs_to :author

  ### Scope Methods ###
  scope :find_by_identifier, ->(identifier) { where(identifier: identifier) }
  scope :order_by_author, -> { joins(:author).merge(Author.order(name: :asc))}
  scope :order_by_title, -> { order(title: :asc)}
  scope :top_rated, -> { joins(:user_books, :reviews).merge(Review.where("rating > 3")).uniq }

  ### Return Top Read Books ###
  def self.top_read
    UserBook.top_read_books.collect { |userbook| userbook.book }
  end

  ### Building and Updating Associations ###
  def author_name=(author_name)
    self.author = Author.find_or_create_by(name: author_name)
  end

  def genre_name=(genre_name)
    self.genre = Genre.find_or_create_by(name: genre_name)
  end

  def user_id=(user_id)
    self.users << User.find(user_id)
    self.save
  end

  ### Ratings ###
  def average_rating
    ratings = self.reviews.collect { |review| review.rating }
    ratings.inject{ |sum, el| sum + el }.to_f / ratings.size
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_login   # Require login before all actions
  before_action :valid_book, only: [:show]

  ### List books from all users
  def index  
    @filter = params[:filter] || "order_by_title"
    @books = Book.send(@filter)    # Filter book index based on a filter param - default is order by title
  end

  ### Show search results when user searches for a new book by title, with option for user to add books to their collection
  def new_search
    @books = BookFinder.search_google_books_by_title(params[:search])             # Instantiate book instances from Google Books search results (by title)
    if @books.empty?                                                              # Flash an error if Google does not return any books and redirect to user path
      flash[:alert] = "We can't find '#{params[:search]}' - please try again."    
      redirect_to user_path(current_user)
    end
  end

  ### Show details of a specific book from search before the user decides to commit it to their collection
  def show_search
    @book = BookFinder.search_google_books_by_identifier(params[:identifier])     # Instantiate book instance from Google Books search (by Google identifier)
  end

  ### Find or create books user chooses to add to their collection
  def create_search
    @book = Book.where(identifier: params[:book][:identifier]).first_or_create(book_params)  # Find or create a book instance based on Google identifier
    current_user.books << @book if !current_user.books.include?(@book)
    redirect_to user_path(current_user)                                                      # Redirect to user show page 
  end

  ### Show details of a specific book in any users collection
  def show
    @book = Book.find(params[:id])                                            # Find Book instance from id in params
    @userbook = UserBook.find_by(user_id: current_user.id, book_id: @book.id) # Find UserBook instance associated with current user and book to display the current user's book activity
  end

  ### Show popular books
  def popular

  end

  ### Update book attributes
  def update
    @book = Book.find(params[:id]).update(book_params)  # Find book and update with book_params
    redirect_to user_path(current_user)                 # Redirect to User Show page
  end

  ### Remove book from current user's collection
  def destroy
    @book = Book.find(params[:id])                           # Find current book and userbook associated with current book and user 
    @userbook = @book.user_books.find_by(user: current_user).remove_book_from_shelves.destroy   # Remove book from user shelves and user collection
    @book.destroy if @book.users.empty?                      # Destroy book if it is no longer associated with any users
    redirect_to user_path(current_user)                      # Redirect to User show page
  end


  private

  def book_params(*args)
    params.require(:book).permit(:title, :pages, :description, :cover_image, :identifier, :genre_name, :author_name, :user_id)
  end
  
end

app/helpers/books_helper.rb
module BooksHelper

  # Shows button for user to add or remove book from their collection on show and index pages
  def add_or_remove_button(book)
    if !book.id && current_user_has_book?(book)                          
      render 'books/form_remove_from_collection', {book: Book.find_by(identifier: book.identifier)}     # Remove button if search result is already in the user's collection
    elsif !book.id && !Book.find_by(identifier: book.identifier)
      render 'books/form_new_from_search', {book: book}           # Add button if book is a search results and isn't in any users collection
    elsif !current_user_has_book?(book)
      render 'books/form_add_to_collection', {book: book}         # Add button if book doesn't belong to current user but does belong to other suers
    else
      render 'books/form_remove_from_collection', {book: book}    # Remove button if book belongs to user and isn't a search result
    end
  end

  # Returns instance of book that belongs to the current user if they have the book
  def current_user_has_book?(book)
    current_user.books.find_by(identifier: book.identifier)
  end

  # Returns array of current user books that aren't on a shelf
  def unsorted_books(user)
    user.books - user.shelves.collect{ |shelf| shelf.books }.flatten.uniq
  end
 
  # return boolean if user has finishe book or not
  def current_user_finished_book(book)
    finished = UserBook.find_user_book_activity(current_user.id, book.id).finished_book if current_user_has_book?(book)
  end
end

app/views/books/_add_to_collection.html.erb
<!-- Form to add an existing book to users collection --> 
<%=form_for book do |f|%>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "Add to My Books", class: 'button-small', id: book.identifier %>
<% end %>

app/views/books/_book_grid.html.erb
<!-- Display a collection of books in a grid --> 
<div class="grid">
  <!-- ******** Book Grid  ******** -->
  <% books.each do |book| %>
    <!-- ******** Book Grid Item ******** -->
    <div class="grid-item" >
      <!-- Image -->
      <%= link_to image_tag(book.cover_image), (search ? book_search_path(book.identifier) : book_path(book)) %>
      
      <!-- Read Label if Read -->
      <% if !search && current_user_finished_book(book) %>
        <div class='book-read'>Read</div>
      <% end %>

      <!-- Title, Author -->
      <p class='title-label'><%= link_to book.title,  (search ? book_search_path(book.identifier) : book_path(book)) %></p>
      <p class='author-label'><%= book.author.name %></p>
      
      <!-- Button to add or remove book from collection -->
      <div class='button-grid'> <%= add_or_remove_button(book) %> </div>
    </div> <!-- grid-item -->
  <% end %>
</div> <!-- grid -->

app/views/books/_form.html.erb
<%=form_for book do |f|%>
  <%= f.hidden_field :title, value: book.title %>
  <%= f.hidden_field :pages, value: book.pages %>
  <%= f.hidden_field :author_name, value: book.author.name %>
  <%= f.hidden_field :genre_name, value: book.genre.name %>
  <%= f.hidden_field :description, value: book.description %>
  <%= f.hidden_field :pages, value: book.pages %>
  <%= f.hidden_field :cover_image, value: book.cover_image %>
  <%= f.hidden_field :identifier, value: book.identifier %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "Add to My Books", class: 'button-small', id: book.identifier %>
<% end %>

app/views/books/_form_add_to_collection.html.erb
<!-- Form to add an existing book to users collection --> 
<%=form_for book do |f|%>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :identifier, value: book.identifier %>
  <%= f.submit "Add to My Books", class: 'button-small', id: book.identifier %>
<% end %>

app/views/books/_form_new_from_search.html.erb
<!-- Form to add a new book from a Google search to users collection --> 

<%=form_for book, url: create_book_search_path do |f|%>
  <%= f.hidden_field :title, value: book.title %>
  <%= f.hidden_field :pages, value: book.pages %>
  <%= f.hidden_field :author_name, value: book.author.name %>
  <%= f.hidden_field :genre_name, value: book.genre.name %>
  <%= f.hidden_field :description, value: book.description %>
  <%= f.hidden_field :pages, value: book.pages %>
  <%= f.hidden_field :cover_image, value: book.cover_image %>
  <%= f.hidden_field :identifier, value: book.identifier %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "Add to My Books", class: 'button-small', id: book.identifier %>
<% end %>

app/views/books/_form_remove_from_collection.html.erb
<!-- Form to remove a book from users collection --> 
<%= form_tag("/books/#{book.id}", method: 'delete') do %>
  <%= submit_tag 'Remove from My Books', class: 'button-small', id: book.identifier %>
<% end %>

app/views/books/_form_shelves.html.erb
  <div class="book-info">
    <!-- Form to let user choose which shelves a book belongs to -->
    <%= form_for userbook, url: user_book_path(userbook) do |f| %>

      <!-- List of checkboxes of users current shelves -->
      <div class="book-fact checkbox-list checks">
        <%= f.collection_check_boxes :shelf_ids, current_user.shelves, :id, :name %>
      </div>

      <!-- Text field to add new shelf -->
      <h3>Add a New Shelf </h3>
      <div class="book-fact">
        <%= f.text_field :shelf_name %>
      </div>

      <!-- Submit -->
      <%= f.submit "Update Shelves", class: 'button' %>
    <% end %>
  </div>

app/views/books/_new_form.html.erb
<%=form_for book do |f|%>
  <%= f.hidden_field :title, value: book.title %>
  <%= f.hidden_field :pages, value: book.pages %>
  <%= f.hidden_field :author_name, value: book.author.name %>
  <%= f.hidden_field :genre_name, value: book.genre.name %>
  <%= f.hidden_field :description, value: book.description %>
  <%= f.hidden_field :pages, value: book.pages %>
  <%= f.hidden_field :cover_image, value: book.cover_image %>
  <%= f.hidden_field :identifier, value: book.identifier %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "Add to My Books", class: 'button-small', id: book.identifier %>
<% end %>

app/views/books/_remove_from_collection.html.erb
<!-- Form to remove a book from users collection --> 
<%= form_tag("/books/#{book.id}", method: 'delete') do %>
  <%= submit_tag 'Remove from My Books', class: 'button-small', id: book.identifier %>
<% end %>

app/views/books/_star_rating.html.erb
<!-- show star rating w/ star icons --> 
<span class="fa fa-star <%=(rating > 0) ? 'checked' : 'unchecked' %>"></span>
<span class="fa fa-star <%=(rating > 1) ? 'checked' : 'unchecked' %>"></span>
<span class="fa fa-star <%=(rating > 2) ? 'checked' : 'unchecked' %>"></span>
<span class="fa fa-star <%= (rating > 3) ? 'checked' : 'unchecked' %>"></span>
<span class="fa fa-star <%= (rating > 4) ? 'checked' : 'unchecked' %>"></span>

app/views/books/index.html.erb
<div class='sub-section'>
  <h1>All Books</h1>

<!-- *********************  Select Book Filter / Order  ********************* -->
  <%= form_tag('/books', method: 'get') do %>
    <div class='buttons'>
      <%= select_tag "filter", 
        "<option #{'selected = "selected"' if @filter == 'order_by_title'} value=order_by_title>Order by Title</option>
         <option #{'selected = "selected"' if @filter == 'order_by_author'} value=order_by_author>Order by Author</option>
         <option #{'selected = "selected"' if @filter == 'top_rated'} value=top_rated>Top Rated</option>".html_safe,
        class: "button" %>
      <%= submit_tag "Apply", class: "button-select" %>
    </div>
  <% end %>
</div>

<!-- *********************  Book Grid ********************* -->
<%= render 'grid', {books: @books, search: false} %>

app/views/books/new.html.erb
<h1>Results for '<%=params[:search]%>' </h1>

<div class="grid">
  <% @books.each do |book| %>
    <div class="grid-item" >
      <%= link_to image_tag(book.cover_image), search_show_path(book.identifier) %>
      <p class='title-label'><%= link_to book.title, search_show_path(book.identifier) %></p>
      <p class='author-label'><%= book.author.name %></p>
      <%= render 'form', {book: book} %>
    </div> <!-- grid-item -->
  <% end %>
</div> <!-- grid -->

app/views/books/search.html.erb
<%=@book.title %>

app/views/books/show_search.html.erb
<!-- Show details on a book from search results -->
<%= render 'books/details', {book: @book, search: true} %>