config/routes.rb
Rails.application.routes.draw do
  ### Home
  get '/', to: 'users#home', as: 'root'

  ### Users - Signup
  get '/users/new', to: 'users#new', as: 'signup'
  resources :users, only: [:create]

  ### Sign In
  get '/signin', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get "/auth/google_oauth2/callback", to: "sessions#create"

  ### Book - Popular
  get '/books/popular', to: 'books#popular', as: 'most_popular_books'

  ### Books - Index, Show, Update, Destroy
  resources :books, only: [:index, :show, :update, :destroy]

  ### Books - New, Create, Show from Google Search
  get '/books/search/new', to: 'books#new_search', as: 'new_book_search'
  post '/books', to: 'books#create_search', as: 'create_book_search'
  get '/books/search/:identifier', to: 'books#show_search', as: 'book_search'

  ### User Book Activity - Update 
  resources :user_books, only: [:update]

  ### Book Reviews - New, Create, Edit, Update, Destroy
  resources :books, only: [:show] do 
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

  ### Users Shelves - Show
  resources :users, only: [:show] do
    resources :shelves, only: [:show]
  end

  ### Shelves - New, Create, Edit, Update, Destroy
  resources :shelves, except: [:index, :show]

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_login  # Require login before all actions
  before_action :valid_book, only: [:new, :show, :edit]
  before_action :valid_review, only: [:show, :edit]

  ### Render new review form
  def new
    @book = Book.find(params[:book_id])
    redirect_to user_path(current_user) if !current_user.has_book?(@book)
    @review = Review.new()
  end

  ### Create new review for current user based on new form input
  def create
    @review = Review.new(review_params)    # Instantiate review
    
    if @review.save
      redirect_to book_path(@review.book)  # Redirect to book path if review saves
    else
      @book = Book.find(params[:book_id])  # Show errors on new review page if the review does not save
      render 'new'
    end

  end

  ### Render edit form for a review
  def edit
    @book = Book.find(params[:book_id]) # Find book
    @review = Review.find(params[:id])  # Find review
    
    redirect_to book_path(@book) if @review.user != current_user #Redirect user to book show page if they did not create the review
  end

  ### Update review based on edit form input
  def update
    @book = Book.find(params[:book_id]) # Find book
    @review = Review.find(params[:id])  # Find review

    if @review.update(review_params)
      redirect_to book_path(@book)      # Redirect to book path if review saves
    else
      render 'edit'                     # Show errors on edit review page if the review does not save
    end

  end

  ### Delete a review (if it belongs to current user)
  def destroy
    @book = Book.find(params[:book_id])               # Find book
    @review = Review.find(params[:id])                # Find review
    
    @review.destroy if @review.user == current_user   # Destroy the review if it belongs to the current user
    
    redirect_to book_path(@book)                      # Redirect to book show page
  end

  private
  def review_params
    params.require(:review).permit(:title, :rating, :review, :user_book_id)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  # Return the id of the user book a review is associated with
  def user_book_id(book_id, user_id)
    UserBook.find_user_book_activity(user_id, book_id).id
  end

  # Returns current users review of provided book
  def current_users_book_review(book)
    UserBook.find_user_book_activity(current_user.id, book.id).review
  end

end

app/views/reviews/_details.html.erb
<sh1><%=review.title%></sh1>
<sh2><%= render 'books/star_rating', {rating: review.rating} %> </sh2>
<p class="small"><%= review.review %> </p>

app/views/reviews/_form.html.erb
<!-- *********************  Error Messages  ********************* -->
<%= render 'users/errors', {object: review} %>

<!-- *********************  Form  ********************* -->
<%=form_for(review, url: (new_review ? book_reviews_path : book_review_path(book,review))) do |f| %>
  <h2><%= f.label "Title" %></h2>
  <%= f.text_field :title %>
  <h2><%= f.label "Rating (1-5)" %></h2>
  <%= f.text_field :rating %>
  <h2><%= f.label "Review" %></h2>
  <%= f.text_area :review %>
  <%= f.hidden_field :user_book_id, value: user_book_id(book.id, current_user.id)%>
  <%= f.submit "Post Review", class: "button" %>
<% end %>

app/views/reviews/edit.html.erb
<!-- ***  Edit Form  *** -->
<h1>Review <%=@book.title%></h1>
<%= render 'reviews/form', {review: @review, book: @book, new_review: false} %>

app/views/reviews/new.html.erb
<!-- ***  New Form  *** -->
<h1>Review <%=@book.title%></h1>
<%= render 'reviews/form', {review: @review, book: @book, new_review: true} %>