config/routes.rb
Rails.application.routes.draw do
  ### Home
  get '/', to: 'users#home', as: 'root'

  ### Users - Signup
  get '/users/new', to: 'users#new', as: 'signup'
  resources :users, only: [:create]

  ### Sign In
  get '/signin', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get "/auth/google_oauth2/callback", to: "sessions#create"

  ### Book - Popular
  get '/books/popular', to: 'books#popular', as: 'most_popular_books'

  ### Books - Index, Show, Update, Destroy
  resources :books, only: [:index, :show, :update, :destroy]

  ### Books - New, Create, Show from Google Search
  get '/books/search/new', to: 'books#new_search', as: 'new_book_search'
  post '/books', to: 'books#create_search', as: 'create_book_search'
  get '/books/search/:identifier', to: 'books#show_search', as: 'book_search'

  ### User Book Activity - Update 
  resources :user_books, only: [:update]

  ### Book Reviews - New, Create, Edit, Update, Destroy
  resources :books, only: [:show] do 
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

  ### Users Shelves - Show
  resources :users, only: [:show] do
    resources :shelves, only: [:show]
  end

  ### Shelves - New, Create, Edit, Update, Destroy
  resources :shelves, except: [:index, :show]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'bookshelf.ico' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    <title>homeUp</title>
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.0/normalize.min.css">
    
    <!-- stars -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="/stylesheets/main.css" />
    
    <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.7.1/modernizr.min.js"></script>
  </head>

  <body>
    <!-- *********************  Header  ********************* -->
    <header class="clearfix">
      <div class="clearfix">
        <div id="header-background" class="header-background">
        </div> <!-- #header-background -->

        <!-- *** Logo *** -->
        <div class="wrapper">
          <div id="logo">
            <%= image_tag('bookshelf-logo-light.png')%>
          </div> <!-- #logo -->
        </div> <!-- .wrapper -->

        <!-- *** Narbar *** -->
        <div id="navbar">
          <div class="wrapper">
            <nav class="clearfix">
              <%= link_to "My Books", user_path(current_user) %>
              <%= link_to "Browse", books_path %>
            </nav>
          </div> <!-- .wrapper -->
        </div> <!-- #navbar -->

        <!-- *** Searchbox *** -->
        <div id="searchbox">
          <%= form_tag(new_book_search_path, method: 'get', class: 'centered') do %>
              <%= text_field_tag 'search', '', id: 'searchbox-text', placeholder: 'Search for books' %>
              <%= image_submit_tag 'search-icon.png', id: 'searchbox-button' %>
          <% end %>
        </div> <!-- #searchbox -->

        <!-- *** User & Logout button *** -->
        <div id="user">
          <div class="wrapper">
            <%=current_user.name%></br>
            <%=link_to 'Logout', logout_path, class: 'link'%>
          </div> <!-- .wrapper -->
        </div> <!-- .user -->
      </div> <!-- .header-background -->
    </header> <!-- header -->

    <!-- *********************  Page body  ********************* -->
    <div class="wrapper body-background clearfix">
      <section>
        <%= yield %>
      </section>
    </div>

    <!-- ********************************************  Footer  ******************************************** -->
    <footer>
      <small>&copy; 2019 <strong>BookShelf</strong></small>
    </footer>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'bookshelf.ico' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    <title>homeUp</title>
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.0/normalize.min.css">
    <link rel="stylesheet" href="/stylesheets/main.css" />
    <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.7.1/modernizr.min.js"></script>
  </head>

  <body>
    <!-- *********************  Page body (unsplit)  ********************* -->
    <div class="wrapper body-background clearfix">
      <%= yield %>
    </div>

    <!-- ********************************************  Footer  ******************************************** -->
    <footer>
      <small>&copy; 2019 <strong>BookShelf</strong></small>
    </footer>
  </body>
</html>